baseUrl = "https://adam.boscarino.me/"
title = "Adam Boscarino"
canonifyurls = true
theme = "coder"
languageCode = "en-us"
defaultContentLanguage = "en"
googleAnalytics = "UA-112552117-1"
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  info = "Data Engineer - Craft Beer Enthusiast - Sports Fan"
  author = "Adam Boscarino"
  description = 'Personal site for Adam Boscarino'
  keywords = "blog,developer,personal,data,engineer"
  avatarurl = "images/me.jpg"
  hideCredits = false
  hideCopyright = false
  inverted = true

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/ajbosco"

[[params.social]]
  name = "Github"
  icon = "fab fa-github fa-2x"
  weight = 1
  url = "https://github.com/ajbosco"

[[params.social]]
  name = "Gitlab"
  icon = "fab fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/ajboscarino"

[[params.social]]
  name = "Twitter"
  icon = "fab fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/ajbosco/"

[[params.social]]
  name = "linkedin"
  icon = "fab fa-linkedin fa-2x"
  weight = 4
  url = "https://www.linkedin.com/in/adam-boscarino-47267313"

[[params.social]]
  name = "goodreads"
  icon = "fab fa-goodreads fa-2x"
  weight = 5
  url = "https://www.goodreads.com/ajbosco"

[[params.social]]
  name = "email"
  icon = "fas fa-envelope fa-2x"
  weight = 6
  url = "mailto:adam@boscarino.me"

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Work"
    weight = 2
    url = "/work/"
[[menu.main]]
    name = "Talks"
    weight = 3
    url = "/talks/"
[[menu.main]]
    name = "Blog"
    weight = 4
    url  = "/posts/"