baseUrl = "https://adam.boscarino.me/"
title = "Adam Boscarino"
canonifyurls = true
theme = "coder"
languageCode = "en-us"
defaultContentLanguage = "en"
googleAnalytics = "UA-112552117-1"
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
  info = "Data Engineer"
  author = "Adam Boscarino"
  description = 'Personal site for Adam Boscarino'
  keywords = "blog,developer,personal,data,engineer"
  avatarurl = "images/logo.png"
  hideCredits = false
  hideCopyright = false
  colorscheme = "auto"
  custom_css = ["/css/sidebar.css"]

[[params.social]]
  name = "GitHub"
  icon = "fab fa-github fa-2x"
  weight = 1
  url = "https://github.com/ajbosco"

[[params.social]]
  name = "LinkedIn"
  icon = "fab fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/adam-boscarino-47267313"

[[params.social]]
  name = "Twitter"
  icon = "fab fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/ajbosco/"

[[params.social]]
  name = "Medium"
  icon = "fab fa-medium fa-2x"
  weight = 4
  url = "https://medium.com/@ajbosco"

[[params.social]]
  name = "Email"
  icon = "fas fa-envelope fa-2x"
  weight = 5
  url = "mailto:adam@boscarino.me"

[[menu.main]]
    name = "Work"
    weight = 1
    url = "/work/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Talks"
    weight = 4
    url = "/talks/"
[[menu.main]]
    name = "Year in Review"
    weight = 5
    url = "/year-in-review/"
[[menu.main]]
    name = "Writing"
    weight = 6
    url  = "/posts/"